# Your disqus shortname, find it here: https://iometa.disqus.com/admin/settings/general/.
disqus: iometa
# Find your favourite code style here: https://www.jsdelivr.com/package/npm/highlight.js?path=styles.
highlight: https://cdn.jsdelivr.net/npm/highlight.js@10.1.1/styles/solarized-light.css
# Enable busuanzi count? It will record your site's pv and uv.
busuanzi: false
# Google analytics id: https://analytics.google.com/analytics/.
analyticsTrackingID:

  #highlight:
  #enable: true
  #auto_detect: true
  #line_number: true
  #tab_replace: '  '
  #wrap: true
  #hljs: false
  #prismjs:
  #enable: false



  #highlight:
  #enable: true
  #auto_detect: false
  #line_number: true
  # tab_replace: ''
  #wrap: true
  #hljs: false
  #prismjs:
  #enable: false
  #preprocess: true
  #line_number: true
  #tab_replace: ''
